-- Ajouter la colonne video_id
ALTER TABLE board_games ADD COLUMN video_id TEXT;

-- Mettre à jour les video_id pour tous les jeux
UPDATE board_games SET video_id = 'tvI8eFfm6Bk' WHERE name = 'Catan';
UPDATE board_games SET video_id = 'QgX8dwbdiug' WHERE name = 'Ticket to Ride';
UPDATE board_games SET video_id = 'R0Qcma3g9JI' WHERE name = 'Pandemic';
UPDATE board_games SET video_id = 'Gnl2iiu9PZ0' WHERE name = '7 Wonders';
UPDATE board_games SET video_id = 'C9zOpikMSzA' WHERE name = 'Azul';
UPDATE board_games SET video_id = 'Bi5q9YuCEQw' WHERE name = 'Codenames';
UPDATE board_games SET video_id = 'aAjFAySW_oY' WHERE name = 'Wingspan';
UPDATE board_games SET video_id = 'imODmr8GqEQ' WHERE name = 'Dixit';
UPDATE board_games SET video_id = 'PZwI7PyJ5pk' WHERE name = 'Carcassonne';
UPDATE board_games SET video_id = 'UkfnyT848LU' WHERE name = 'Splendor';
UPDATE board_games SET video_id = 'r0EwRhyicyo' WHERE name = 'Terraforming Mars';
UPDATE board_games SET video_id = 'c8tWq0y83oU' WHERE name = 'Love Letter';
UPDATE board_games SET video_id = '_2azdwSTgTA' WHERE name = 'The Crew';
UPDATE board_games SET video_id = 'HXdZ6e21HY4' WHERE name = 'Risk';
UPDATE board_games SET video_id = 'jnM9yf65rpo' WHERE name = 'Kingdomino';
UPDATE board_games SET video_id = 'hjo09iNrWbE' WHERE name = 'Uno';
UPDATE board_games SET video_id = 'ZmNxON3HK4Y' WHERE name = 'Small World';
UPDATE board_games SET video_id = 'FaA-pv2QwJU' WHERE name = 'Cluedo';
UPDATE board_games SET video_id = 'ZjBdWrgXkpI' WHERE name = 'Time''s Up!';
UPDATE board_games SET video_id = 'iIct2o0xtp8' WHERE name = 'Takenoko';
UPDATE board_games SET video_id = 'dVgqOujGpc8' WHERE name = 'Dominion';
UPDATE board_games SET video_id = 'd6Deqf57hOA' WHERE name = 'Gloomhaven';
UPDATE board_games SET video_id = 'kEvS1t9bpEk' WHERE name = '6 qui prend !';
UPDATE board_games SET video_id = 'SKfvpQWBTN0' WHERE name = 'Brass: Birmingham';
UPDATE board_games SET video_id = 'QgX8dwbdiug' WHERE name = 'Les Aventuriers du Rail : Europe';
UPDATE board_games SET video_id = 'vG9-letaXCs' WHERE name = 'Hanabi';
UPDATE board_games SET video_id = 'MtGR-9ITlNM' WHERE name = 'Patchwork';
UPDATE board_games SET video_id = '03PEoNOOsfs' WHERE name = 'Scythe';
UPDATE board_games SET video_id = 'FNddIoRoyZ8' WHERE name = 'Just One';
UPDATE board_games SET video_id = 'Or13pbEfy6I' WHERE name = 'Mysterium';
UPDATE board_games SET video_id = '8VpD9Ke9AWE' WHERE name = 'Agricola';
UPDATE board_games SET video_id = 'CKX2QW5ASzU' WHERE name = 'Exploding Kittens';
UPDATE board_games SET video_id = 'nMeuj6iZanU' WHERE name = 'Santorini';
UPDATE board_games SET video_id = 'B4d14QdwoFE' WHERE name = 'Loup-Garou pour une Nuit';
UPDATE board_games SET video_id = 'e47CWAJwe0M' WHERE name = 'Stone Age';
UPDATE board_games SET video_id = 'Dnd-mZ92yr8' WHERE name = 'Dobble';
UPDATE board_games SET video_id = 'sFx8O2uK3UY' WHERE name = 'Citadelles';
UPDATE board_games SET video_id = 'M4YbypJLJtE' WHERE name = 'Power Grid';
UPDATE board_games SET video_id = 'QvEfUdi3vo4' WHERE name = 'The Mind';
UPDATE board_games SET video_id = '9Fn0m4ic0Pg' WHERE name = 'Qwirkle';
UPDATE board_games SET video_id = '9fxREP0KluI' WHERE name = 'Everdell';
UPDATE board_games SET video_id = 'YmVXgLurPvo' WHERE name = 'Saboteur';
UPDATE board_games SET video_id = 'Npem9N7QUzY' WHERE name = 'Orléans';
UPDATE board_games SET video_id = '4BJv_vDqou8' WHERE name = 'Skyjo';
UPDATE board_games SET video_id = '6IHTgavAvGE' WHERE name = 'Root';
UPDATE board_games SET video_id = 'V27IGRa_9Jg' WHERE name = 'Welcome';
UPDATE board_games SET video_id = '4IDltUngXM4' WHERE name = 'Five Tribes';
UPDATE board_games SET video_id = 'xP0XYo80_74' WHERE name = 'Jungle Speed';
UPDATE board_games SET video_id = 'rBs1owwn57g' WHERE name = 'Great Western Trail';
UPDATE board_games SET video_id = 'ErM2XJC7vjk' WHERE name = 'The Resistance';
UPDATE board_games SET video_id = 'xdQymiuB5-c' WHERE name = 'Jaipur';
UPDATE board_games SET video_id = 'sbYu3QDRvMQ' WHERE name = 'Terraforming Mars: Ares Expedition';
UPDATE board_games SET video_id = '9lv-xSfEe0A' WHERE name = 'Bang!';
UPDATE board_games SET video_id = 'CP1HFNNWpUk' WHERE name = 'Cascadia';
UPDATE board_games SET video_id = 'pHQyQLRscoY' WHERE name = 'Lost Cities';
UPDATE board_games SET video_id = 'HXG_azOnris' WHERE name = 'Concept';
UPDATE board_games SET video_id = 'OQOsbefmfPQ' WHERE name = 'Concordia';
UPDATE board_games SET video_id = 'c8tWq0y83oU' WHERE name = 'Love Letter: Premium';
UPDATE board_games SET video_id = 'tsRsX2cQbBk' WHERE name = 'Survive: Escape from Atlantis';
UPDATE board_games SET video_id = 'bSvgCxXQktA' WHERE name = 'Ark Nova';
UPDATE board_games SET video_id = 'JWd2FuE9G2Y' WHERE name = 'Chinatown';
UPDATE board_games SET video_id = 'wQOgShoAnd4' WHERE name = 'Eclipse';
UPDATE board_games SET video_id = '-WO2yoqn2UA' WHERE name = 'Patchwork Doodle';
UPDATE board_games SET video_id = 'nrS9V8BOYO4' WHERE name = 'Sheriff of Nottingham';
UPDATE board_games SET video_id = 'vPe2f4E70Rg' WHERE name = 'Tzolk''in: The Mayan Calendar';
UPDATE board_games SET video_id = 'ttnvpkrtQn8' WHERE name = 'Alhambra';
UPDATE board_games SET video_id = 'gbbZRuv4Bwo' WHERE name = 'Funkoverse';
UPDATE board_games SET video_id = 'UC_2598ffuDtZubPowX0vrhQ' WHERE name = 'Heaven & Ale';
UPDATE board_games SET video_id = 'mqOQzJEY15w' WHERE name = 'Camel Up';
UPDATE board_games SET video_id = '6luR2yXWggU' WHERE name = 'Tigris & Euphrates';
UPDATE board_games SET video_id = 'Dm07QSE4gm4' WHERE name = 'Through the Ages: A New Story of Civilization';
UPDATE board_games SET video_id = 'mM3b0LGFhQM' WHERE name = 'Obsession';
UPDATE board_games SET video_id = 'KkF9d7YzO9A' WHERE name = 'Azul: Summer Pavilion';
UPDATE board_games SET video_id = 'Ys8LuoKT470' WHERE name = 'Kemet';
UPDATE board_games SET video_id = 'Tt1kJZWoxys' WHERE name = 'Caylus';
UPDATE board_games SET video_id = 'pZfe7FGo_Og' WHERE name = 'Bang! The Dice Game';
UPDATE board_games SET video_id = '6TZkSftLnj4' WHERE name = 'Oriflamme';
UPDATE board_games SET video_id = 'L6YsNsMcdC4' WHERE name = 'Everdell: Pearlbrook';
UPDATE board_games SET video_id = 'qPhmNKCrJcg' WHERE name = 'Shadows over Camelot';
UPDATE board_games SET video_id = 'bg02VrlPZyU' WHERE name = 'Memoir ''44';
UPDATE board_games SET video_id = '4nJMwaWNLVM' WHERE name = 'Spirit Island';
UPDATE board_games SET video_id = 'M_Sd-I98guY' WHERE name = 'Viticulture';
UPDATE board_games SET video_id = 'RSUE4Q8jW9k' WHERE name = 'Clank!';
UPDATE board_games SET video_id = 'bMA4UL1PwyM' WHERE name = 'Quacks of Quedlinburg';
UPDATE board_games SET video_id = 'qK2hGHLyong' WHERE name = 'Pandemic Legacy: Season 1';
UPDATE board_games SET video_id = 'XqFJDnBv7S4' WHERE name = 'Blood Rage';
UPDATE board_games SET video_id = 'lFMY-MeoMA8' WHERE name = 'Betrayal at House on the Hill';
UPDATE board_games SET video_id = '0Jvoa5PLVJE' WHERE name = 'Sushi Go Party!';
UPDATE board_games SET video_id = 'FtqMzkKmoCE' WHERE name = 'Dune: Imperium';
UPDATE board_games SET video_id = 'LHv-Y06s_js' WHERE name = 'Puerto Rico';
UPDATE board_games SET video_id = '_SSrczObxWs' WHERE name = 'Nemesis';
UPDATE board_games SET video_id = 'QKf3Dvaz2EA' WHERE name = 'Century: Spice Road';
UPDATE board_games SET video_id = 'x0H4n28UoQE' WHERE name = 'Photosynthesis';
UPDATE board_games SET video_id = 'GjZH3dxA4kA' WHERE name = 'Mage Knight';
UPDATE board_games SET video_id = 'np11lHh2nak' WHERE name = 'Res Arcana';
UPDATE board_games SET video_id = 'mXGp0jRTVLM' WHERE name = 'Inis';
UPDATE board_games SET video_id = '6vWuu1eSBSs' WHERE name = 'Twilight Imperium (4th Edition)';
UPDATE board_games SET video_id = 'xy7zz3xHQgI' WHERE name = 'Coup';
UPDATE board_games SET video_id = 'wGPC9GiFlsA' WHERE name = 'Architects of the West Kingdom';
UPDATE board_games SET video_id = '1MNthTR2-Hk' WHERE name = 'Calico';
UPDATE board_games SET video_id = 'h3SkMYcInK0' WHERE name = 'Cryptid';
