export const CATEGORY = {
  STRATEGY: 'STRATEGY',
  FAMILY: 'FAMILY',
  COOPERATIVE: 'COOPERATIVE',
  DRAFT: 'DRAFT',
  ABSTRACT: 'ABSTRACT',
  PARTY: 'PARTY',
  RESOURCE_MANAGEMENT: 'RESOURCE_MANAGEMENT',
  DECK_BUILDING: 'DECK_BUILDING',
  WORKER_PLACEMENT: 'WORKER_PLACEMENT',
  ADVENTURE: 'ADVENTURE',
  CARD_GAME: 'CARD_GAME',
  DEDUCTION: 'DEDUCTION',
} as const;

export type Category = (typeof CATEGORY)[keyof typeof CATEGORY];
